import { Highlight } from "@/components/animations/animation";

function Summary() {
	return (
		<section className="h-auto pt-12 flex flex-col items-center lg:text-5xl text-2xl font-thin text-center tracking-wide">
			<Highlight>
				<span>
					With 10 years of experience in software development, I am a seasoned professional with a wide range of expertise. My areas of
					focus include full stack development, mobile development, and data analysis.
				</span>
				<span>
					Throughout my career, I have worked on a variety of projects, ranging from scalable, high-performance APIs and live web
					applications to control panels, web shops, and social media platforms.
				</span>
				<span>
					I am deeply committed to staying up-to-date with the latest advancements in technology and industry trends. I enjoy exploring new
					programming languages, frameworks, and tools, and incorporating them into my work to enhance performance and user experience.
				</span>
				<span>As a developer, I take pride in my ability to create software that is both efficient and user-friendly. </span>
				<span>
					My excellent communication skills and ability to collaborate effectively with cross-functional teams have been critical to my
					success.
				</span>
				<span>
					Working closely with designers, product managers, and other developers, I have delivered high-quality software solutions that meet
					and exceed the expectations of our clients.
				</span>

				<span>
					My ultimate goal is to leverage my skills and experience to develop software that solves real-world problems and delivers value to
					users.
				</span>
				<span>
					I am passionate about creating products that make a difference, and I look forward to the opportunity to contribute to your
					organization.
				</span>
				<span>
					For the past 5 years, I have been employed as a software developer at ImWind, an Austrian company that serves clients throughout
					Europe.
				</span>
				<span>
					In this role, I have gained valuable experience working in a variety of environments and programming languages, and have handled
					large volumes of data generated by wind turbines.
				</span>
				<span>
					My responsibilities include assisting clients with visualizing, creating, modifying, and deleting data, automating workflows to
					generate daily reports, developing custom algorithms as per their requirements, and more.
				</span>
				<span>
					I take great pride in my ability to deliver high-quality software solutions that meet and exceed the expectations of our clients.
				</span>
			</Highlight>
		</section>
	);
}

export default Summary;
